allowedLicenses:
  - Apache-2.0
ignoreFiles:
  - receiver/**/generated_metrics.go
  - receiver/**/generated_metrics_test.go
  - receiver/mongodbreceiver/**/*.go
  - receiver/sapnetweaverreceiver/**/*.go
sourceFileExtensions:
  - go
  - ps1
  - sh
